services:
  image-relay:
    build: .
    container_name: image-relay
    restart: unless-stopped
    ports:
      - "7799:7799"
    environment:
      - PORT=7799
      - BASE_URL=https://img.kenluu.org
      - TTL_HOURS=2
      - MAX_SIZE_MB=10
    labels:
      - traefik.enable=true
      - traefik.http.routers.image-relay.rule=Host(`img.kenluu.org`)
      - traefik.http.routers.image-relay.entrypoints=websecure
      - traefik.http.routers.image-relay.tls.certresolver=traefik-main
      - traefik.http.services.image-relay.loadbalancer.server.port=7799
    networks:
      - frontend

networks:
  frontend:
    external: true
